FROM mcr.microsoft.com/playwright:v1.56.1-noble

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.18.3 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm postinstall

CMD ["pnpm", "test:e2e"]
